services:
  _defaults:
    autowire: true
    autoconfigure: true

  Snoke\OAuthServer\:
    autowire: true
    autoconfigure: true
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

