services:
  _defaults:
    autowire: true
    autoconfigure: true

  Snoke\OAuthServer\:
    autowire: true
    autoconfigure: true
    resource: '../../'

  mapping.listener:
    class: Snoke\OAuthServer\EventListener\LoadClassMetadataListener
    arguments: []
    tags:
      - { name: doctrine.event_listener, event: loadClassMetadata, lazy: true }
